### PR TITLE
upgrade the project to .NET 8.0

### PR DESCRIPTION
**Pull request by svecs132**
everything in the program works after the upgrade

### CODE REVIEW

**Comment by greyshirtguy** [comment]
.net 8 means that people now have to install that to run the app on windows 10 right?

I tend to hold back on version upgrades  unless it offers a feature the app needs!

that way, more people can just download and run on any windows box!! (Without any extra steps) - fwiw, I prefer that!!!

**Comment by svecs132** [comment]
I wanted to add a package to the program but the `dotnet add package` command didn't work and from what I found, the best way to fix it (among other benefits) would be to upgrade the .NET version

**Comment by svecs132** [comment]
but I'm a beginner in the .NET world so you probably know better

**Comment by svecs132** [comment]
also I just read some stuff about ways to publish .NET projects and I thought we could make two versions (build two versions for each release):

- a smaller, **runtime-dependent** build (optionally with a text file describing how to install the runtime if someone wants to use that version but doesn't have the runtime yet)
- a larger, portable, **self-contained** version (I've just tried publishing it in that way and then it ran without any problems on my Win10 VM where the runtime-dependent version didn't (I intentionally didn't install the runtime there for testing))

and just some notes about the versions and the differences...

is that a good idea? @greyshirtguy

**Comment by greyshirtguy** [comment]
Hmm this sound fine!



Background:
I've been out of touch for years!....and not up to speed with .NET platform changes over the last 5 years!

Back in the day, I've always loved the old .net framework being included in Win10 - so that simple apps with no extra libraries just work... I really loved that super simple app would just work as a single .exe file (nothing else!!)
Copy the single .exe and run was something that I loved.

This app is one level above that - you need  a "few" library .dll files to be present in same folder as .exe (but still NOTHING to install).....

I also prefer to use _least 3rd party libraries as possible_ (just a weird preference I have)....

That said, the self contained .net executable sounds interesting and is probably a good option.
I'm not super fussed. (I've probably got old/wrong ideas that might need updating!! - but I will stick to idea to use least 3rd party libraries/packages as possible - only add what is absolutely needed for the app to work)

**Comment by svecs132** [comment]
I wanted to add a package called `DarkNet` which allows you to change the color of the window title bar and borders (either to the default windows dark theme -- think Win11 notepad -- or custom colors) without having to replace the whole title bar with custom elements (i think that is called a window chrome or something and in that case I could remove the default window decorations but I would have to recreate everything (window close/minimize/... buttons etc.) from scratch just with different colors) and I needed that for the dark mode I'm working on on the `dark-mode` branch

but of course dark mode title bar isn't that important so we don't have to do it, I just like it more

**Comment by svecs132** [comment]
by the way I'm making the dark mode with a lot of inspiration from the ProPresenter UI and colors :)

**Comment by svecs132** [comment]
@greyshirtguy so am I allowed to merge this?

**Comment by greyshirtguy** [comment]
If the "setup" instructions are no more complex than they are now for Win10-11 (just extract files and run) then I am happy - go ahead.

**Comment by svecs132** [comment]
well for the self contained version it's identical, just the file contains the runtime as well and for the dependent version we just add that the version needs the runtime and a link to its download if someone wants to use it like that and doesn't have the runtime yet

**Comment by greyshirtguy** [comment]
Sounds good

**Comment by svecs132** [comment]
so the most basic run option has the same instructions but people who have the runtime already can just run the other version

**Pull request merged**
